[[redirects]]
  from = "https://matrix.lenicyl.tk/"
  to = "https://matrix.to/#/#lenicyl:matrix.org"
  status = 301
  force = true
[[redirects]]
  from = "https://lenicyl.tk/"
  to = "https://ddg.gg"
  status = 301
  force = true
